apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    meta.helm.sh/release-name: daily-backup
    meta.helm.sh/release-namespace: test-cronjob
  creationTimestamp: "2024-03-25T09:35:50Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    dept: personaltest
    env: qa
    product: schedule
    repo: daily-backup2
    type: cronjob2
  managedFields:
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
          f:dept: {}
          f:env: {}
          f:product: {}
          f:repo: {}
          f:type: {}
      f:spec:
        f:concurrencyPolicy: {}
        f:failedJobsHistoryLimit: {}
        f:jobTemplate:
          f:spec:
            f:backoffLimit: {}
            f:template:
              f:metadata:
                f:labels:
                  .: {}
                  f:dept: {}
                  f:env: {}
                  f:product: {}
                  f:repo: {}
                  f:type: {}
              f:spec:
                f:containers:
                  k:{"name":"daily-backup"}:
                    .: {}
                    f:image: {}
                    f:imagePullPolicy: {}
                    f:name: {}
                    f:resources:
                      .: {}
                      f:limits:
                        .: {}
                        f:cpu: {}
                        f:memory: {}
                      f:requests:
                        .: {}
                        f:cpu: {}
                        f:memory: {}
                    f:terminationMessagePath: {}
                    f:terminationMessagePolicy: {}
                f:dnsPolicy: {}
                f:restartPolicy: {}
                f:schedulerName: {}
                f:securityContext: {}
                f:serviceAccount: {}
                f:serviceAccountName: {}
                f:terminationGracePeriodSeconds: {}
        f:schedule: {}
        f:successfulJobsHistoryLimit: {}
        f:suspend: {}
    manager: helm
    operation: Update
    time: "2024-03-25T09:35:50Z"
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:active: {}
        f:lastScheduleTime: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2024-03-25T09:36:00Z"
  name: daily-backup
  namespace: test-cronjob
  resourceVersion: "115540379"
  uid: 35ff3ae4-8096-4e0f-b60a-43fdb9703819
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 0
      template:
        metadata:
          creationTimestamp: null
          labels:
            dept: personaltest
            env: qa
            product: schedule
            repo: daily-backup2
            type: cronjob2
        spec:
          containers:
          - image: eugeneyiew128/daily-backup-cronjob:dev_2024032566
            imagePullPolicy: Always
            name: daily-backup
            resources:
              limits:
                cpu: 50m
                memory: 50Mi
              requests:
                cpu: 50m
                memory: 50Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: logging-ksa
          serviceAccountName: logging-ksa
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  active:
  - apiVersion: batch/v1
    kind: Job
    name: daily-backup-28522656
    namespace: test-cronjob
    resourceVersion: "115540377"
    uid: 6c4bc6fd-8ca4-479e-9f27-c59cd6013f2d
  lastScheduleTime: "2024-03-25T09:36:00Z"