{{- if .Values.configmap }}
{{- range .Values.configmap }}
{{- $name := .name }}
{{- $namespace := .namespace }}
{{- $labels := .labels }}
{{- $data := .data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $namespace | default "default" }}
  labels:
  {{- with $labels }}
    env: {{ .env }}
    type: {{ .type }}
    dept: {{ .dept }}
    product: {{ .product }}
    repo: {{ .repo }}
    {{- if .tag }}
    tag: {{ .tag }}
    {{- end }}
  {{- end }}
data:
  {{- range $key, $value := $data }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  # {{ $data }}
{{- end }}
{{- end }}
