{{- if .Values.job }}
apiVersion: batch/v1
kind: CronJob
metadata:
  {{- if .Values.labels }}
  labels:
    {{- include "labels" . | indent 4 }}
  {{- end }}
  # Cronjob name
  name: {{ .Values.name }}
  # namespace
  namespace: {{ .Values.namespace | default "default" }}
spec:
  schedule: {{ .Values.job.schedule | toYaml | default "* * * * *" }}
  concurrencyPolicy: Allow
  suspend: false
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit | default 10 }}
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit | default 10 }}
  selector:
    matchLabels:
      {{- if .Values.labels }}
      # deployment 與 pod 相認的 labels
      {{- include "labels" . | indent 6 }}
      {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- if .Values.labels }}
          labels:
            {{- include "labels" . | indent 12 }}
          {{- end }}
        spec:
          containers:
          - name: {{ .Values.name }}
            image: {{ .Values.job.image.repository | default "nginx:latest" }}
            imagePullPolicy: {{ .Values.job.image.imagePullPolicy | default "Always" }}
            resources:
              {{- include "resources" . | indent 14 }}
          restartPolicy: OnFailure 
{{- end }}