{{- if .Values.secrets }}
# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.labels }}
  labels:
    {{- include "labels" . | indent 4 }}
  {{- end }}
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
