name: Scheduled Job

on:
  schedule:
    - cron: '0 * * * *'  # This runs the job every hour

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "This is a scheduled job!"
          # Add your commands here

